version: 2

formats:
   - epub
   - pdf

build:
  image: dev

python:
  version: 3.7
  install:
     - method: pip
       path: .
     - requirements: requirements.txt
  system_packages: true

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true